# Generated by Django 4.0.4 on 2022-05-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Availabe',
            new_name='Available',
        ),
    ]
