# Generated by Django 4.0.4 on 2022-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_availabe_employee_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('Reason', models.TextField()),
            ],
        ),
    ]
